# Generated by Django 4.0.10 on 2023-07-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'advertisements'},
        ),
    ]
