# Generated by Django 4.0.10 on 2023-07-29 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0002_alter_advertisement_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'advertisements', 'verbose_name_plural': 'advertisements'},
        ),
    ]
